server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8769/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: loan-service
          url: lb://loan-service
          predicates:
            - Path=/loanRecord/**

        - id: payment-service
          url: lb://payment-service
          predicates:
            - Path=/paymentRecord/**

        - id: account-service
          url: lb://account-service
          predicates:
            - Path=/userAccount/**
